language: cpp

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  - sudo apt-get update -qq
  

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  
  - sudo apt-get install boost1.55

script: 
  - $CXX --version
  - cmake . && make